### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by jaxxstorm** [udhos/jazigo#1]
Hey, this is a really cool project, would love to give it a go!

Unfortunately, the build is failing:

```
# github.com/udhos/jazigo/dev
../../go/src/github.com/udhos/jazigo/dev/model.go:65: undefined: registerModelLinux
FAIL	github.com/udhos/jazigo/dev [build failed]
```

**Comment by udhos** [comment]
Hi!

Which command line call did issue that error?

For reference, ihis is what I am seeing:

    lab@ubu:~$ echo $GOPATH
    /home/lab/go
    lab@ubu:~$ go version
    go version go1.8rc1 linux/386
    lab@ubu:~$ go get github.com/udhos/jazigo
    package github.com/udhos/jazigo: no buildable Go source files in /home/lab/go/src/github.com/udhos/jazigo
    lab@ubu:~$ go install github.com/udhos/jazigo/jazigo
    lab@ubu:~$

**Comment by udhos** [comment]
@jaxxstorm can this issue be closed?

**Comment by jaxxstorm** [comment]
Seems to be working now, yes.

```
echo $GOPATH   
/Users/Lee/go
go version go1.7.4 darwin/amd64
go get github.com/udhos/jazigo
can't load package: package github.com/udhos/jazigo: no buildable Go source files in /Users/Lee/go/src/github.com/udhos/jazigo
 go install github.com/udhos/jazigo/jazigo
$GOPATH/bin/jazigo 
2017/01/17 16:46:33 main: could not get exclusive lock: exclusiveLock: lock failure: '/var/jazigo/etc/jazigo.conf.lock': open /var/jazigo/etc/288273065: no such file or directory
panic: main: refusing to run without exclusive lock

goroutine 1 [running]:
panic(0x412760, 0xc42016caa0)
	/usr/local/Cellar/go/1.7.4_2/libexec/src/runtime/panic.go:500 +0x1a1
main.main()
	/Users/Lee/go/src/github.com/udhos/jazigo/jazigo/main.go:161 +0x25d7
```

Obviously that last issue is due to not having a config file :)

**Comment by udhos** [comment]
BTW, easiest way to get past that last error is:

    export JAZIGO_HOME=/some/path
    cd $JAZIGO_HOME
    mkdir etc repo log
    $GOPATH/bin/jazigo
