### ISSUE TITLE
Build Issue on MacOS

### ISSUE THREAD

**Issue by kevin1969** [udhos/jazigo#2]
Attempting to install I get this message.
`$ go install github.com/udhos/jazigo/jazigo`
`src/github.com/udhos/jazigo/dev/model.go:66: undefined: registerModelLinux`

go version go1.7.5 darwin/amd64
Yosemite 10.10.5
Darwin Kernel Version 14.5.0

**Comment by kevin1969** [comment]
Using the build.sh I get a bit more detail. 

16. install
# github.com/udhos/jazigo/dev
dev/model.go:66: undefined: registerModelLinux
17. test dev
`# github.com/udhos/jazigo/dev`
`dev/model.go:66: undefined: registerModelLinux
FAIL	github.com/udhos/jazigo/dev [build failed]
18. test store
JAZIGO_S3_REGION undefined -- for S3 testing, set JAZIGO_S3_REGION=region
JAZIGO_S3_FOLDER undefined -- for S3 testing, set JAZIGO_S3_FOLDER=bucket/folder
ok  	github.com/udhos/jazigo/store	6.023s`

**Comment by kevin1969** [comment]
Seems to be a problem with the model_linux.go module. Not sure exactly what but commenting it out in the model.go module allows the 'go test github.com/udhos/jazigo/dev' to complete.

**Comment by udhos** [comment]
I think I've found the issue.
The _linux.go suffix restricted that file to be compiled only under Linux.
I have just renamed it to prevent such a build issue.
Can you please retry the latest commit?

**Comment by kevin1969** [comment]
That was it.   Thanks!!

**Comment by udhos** [comment]
Fixed by https://github.com/udhos/jazigo/commit/cab24f30c6574a427b54e269e551e79b7571b4c2
