### ISSUE TITLE
deviceImport problem with lock failure

### ISSUE THREAD

**Issue by sifuelIDDQD** [udhos/jazigo#3]
Hi, 

Thanks for the software and seems to be runnig fine apart from couple of problems.. this and other issue which will be coming shortly

Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 GNU/Linux
installed jazigo today with Quick Start - Short version instructions

Working fine, connections are fine, login credentials are working and manual device entry works.

But when i use deviceimport feature:

table.txt (copy from the git site https://github.com/udhos/jazigo) is used for testing the import of nodes to jazigo:

model   id   hostport      transports username password enable-password
cisco-ios node ip ssh username password xxxx

jazigo not running or running.. same error appears

2018/01/22 13:59:49 main: could not get exclusive lock: exclusiveLock: lock failure: '/var/jazigo/etc/jazigo.conf.lock': open /var/jazigo/etc/747543250: no such file or directory
panic: main: refusing to run without exclusive lock

goroutine 1 [running]:
main.main()
        /locationtoinstallfolder/go/src/github.com/udhos/jazigo/jazigo/main.go:168 +0x2551

**Comment by udhos** [comment]
Maybe you have set JAZIGO_HOME properly when running in 'server' mode, but not when running with -deviceImport ?

Please show your full command line for running in both cases ('normal server mode' vs '-deviceImport mode').
