### ISSUE TITLE
Fetching a big config from c6509 cisco

### ISSUE THREAD

**Issue by sifuelIDDQD** [udhos/jazigo#4]
For some reason, telnet connection works and it fetches the configuration nicely. 

Only problem is that the config is quite big and it does not backup entirely (about half comes through and about a half is missing from the end)

What could be the cause?

I increased the maxconfigloadsize: 20000000
But still it stops at config size 46938

**Comment by udhos** [comment]
Do you mean the issue affects only SSH, not TELNET?

Can you post logs for the problem?

**Comment by udhos** [comment]
Also you can set the 'debug' device property in order to enable verbose logging.

![image](https://user-images.githubusercontent.com/2634722/35309135-f4a2f330-0091-11e8-9567-416d9001da01.png)
