### ISSUE TITLE
How can i delete a device?

### ISSUE THREAD

**Issue by shagy234** [udhos/jazigo#6]
I couldnt find a way to delete a device form the GUI or on the files.

How can i do it?

**Comment by udhos** [comment]
You can set the field `deleted` to `true` in the Device Property tab:

![image](https://github.com/udhos/jazigo/assets/2634722/1a165663-395d-4d36-903a-7fb5c241d611)

**Comment by udhos** [comment]
If you need to delete multiple devices, you can also use the command-line:

```
# mark as deleted
cat devices_to_delete.txt | JAZIGO_HOME=$PWD ~/go/bin/jazigo -deviceDelete

# fully remove from device table
cat devices_to_purge.txt | JAZIGO_HOME=$PWD ~/go/bin/jazigo -devicePurge
```
