### ISSUE TITLE
Install Help

### ISSUE THREAD

**Issue by tpolim008** [udhos/jazigo#8]
hello, I wanted to try out this tool which seems pretty simple and basic. Im installing this on a RedHat6 server. When I attempt the runonce command or the forever startup command I get the following error.

GOPATH/bin/jazigo -runOnce
-bash: GOPATH/bin/jazigo: No such file or directory

[root@malowntx-netengsrv02 ~]# yum install go
Loaded plugins: fastestmirror, langpacks, product-id, search-disabled-repos, subscription-manager

This system is not registered with an entitlement server. You can use subscription-manager to register.

Loading mirror speeds from cached hostfile
Package golang-1.19.10-1.el7.x86_64 already installed and latest version
Nothing to do
[root@malowntx-netengsrv02 ~]# wget https://go.dev/dl/go1.20.5.linux-amd64.tar.gz 
--2023-08-03 08:24:09--  https://go.dev/dl/go1.20.5.linux-amd64.tar.gz
Resolving zonepxy-ch2-01g.cable.comcast.com (zonepxy-ch2-01g.cable.comcast.com)... 10.22.32.13
Connecting to zonepxy-ch2-01g.cable.comcast.com (zonepxy-ch2-01g.cable.comcast.com)|10.22.32.13|:8443... connected.
Proxy request sent, awaiting response... 302 Found
Location: https://dl.google.com/go/go1.20.5.linux-amd64.tar.gz [following]
--2023-08-03 08:24:12--  https://dl.google.com/go/go1.20.5.linux-amd64.tar.gz
Connecting to zonepxy- connected.
Proxy request sent, awaiting response... 200 OK
Length: 100203442 (96M) [application/x-gzip]
Saving to: â€˜go1.20.5.linux-amd64.tar.gzâ€™

100%[===============================================================================================================================================================================================>] 100,203,442 1.96MB/s   in 50s    

2023-08-03 08:25:02 (1.92 MB/s) - â€˜go1.20.5.linux-amd64.tar.gzâ€™ saved [100203442/100203442]

[root@malowntx-netengsrv02 ~]# tar -xzf go1.20.5.linux-amd64.tar.gz 
[root@malowntx-netengsrv02 ~]# mv go /usr/local 
[root@malowntx-netengsrv02 ~]# export GOROOT=/usr/local/go 
[root@malowntx-netengsrv02 ~]# export GOPATH=$HOME/Projects/Proj1 
[root@malowntx-netengsrv02 ~]# export PATH=$GOPATH/bin:$GOROOT/bin:$PATH 
[root@malowntx-netengsrv02 ~]# go version 
go version go1.20.5 linux/amd64
[root@malowntx-netengsrv02 ~]# go env 
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/Projects/Proj1/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/Projects/Proj1"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.5"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build60929866=/tmp/go-build -gno-record-gcc-switches"
[root@malowntx-netengsrv02 ~]# 
[root@malowntx-netengsrv02 ~]# git clone https://github.com/udhos/jazigo
Cloning into 'jazigo'...
remote: Enumerating objects: 1749, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 1749 (delta 5), reused 13 (delta 4), pack-reused 1722
Receiving objects: 100% (1749/1749), 349.70 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1171/1171), done.
[root@malowntx-netengsrv02 ~]# cd jazigo
[root@malowntx-netengsrv02 jazigo]# go install ./...
go: downloading github.com/aws/aws-sdk-go v1.44.266
go: downloading github.com/udhos/equalfile v0.0.0-20180725151512-a22d6261a8df
go: downloading golang.org/x/crypto v0.9.0
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/icza/gowut v1.3.0
go: downloading github.com/udhos/difflib v0.0.0-20170223180222-9237ff6aafff
go: downloading github.com/udhos/lockfile v0.0.0-20160928001432-1d49c987357a
go: downloading github.com/jmespath/go-jmespath v0.4.0
[root@malowntx-netengsrv02 jazigo]# export JAZIGO_HOME=$HOME/jazigo
[root@malowntx-netengsrv02 jazigo]# mkdir $JAZIGO_HOME
mkdir: cannot create directory â€˜/root/jazigoâ€™: File exists
[root@malowntx-netengsrv02 jazigo]# cd $JAZIGO_HOME
[root@malowntx-netengsrv02 jazigo]# mkdir etc repo log www
mkdir: cannot create directory â€˜wwwâ€™: File exists
[root@malowntx-netengsrv02 jazigo]# mkdir etc repo log www
mkdir: cannot create directory â€˜etcâ€™: File exists
mkdir: cannot create directory â€˜repoâ€™: File exists
mkdir: cannot create directory â€˜logâ€™: File exists
mkdir: cannot create directory â€˜wwwâ€™: File exists
[root@malowntx-netengsrv02 jazigo]# cp ~/go/src/github.com/udhos/jazigo/www/* $JAZIGO_HOME/www
cp: cannot stat â€˜/root/go/src/github.com/udhos/jazigo/www/*â€™: No such file or directory
[root@malowntx-netengsrv02 jazigo]# cd $JAZIGO_HOME/www
[root@malowntx-netengsrv02 www]# wget https://raw.githubusercontent.com/udhos/jazigo/master/www/fail-small.png
--2023-08-03 08:28:11--  https://raw.githubusercontent.com/udhos/jazigo/master/www/fail-small.png
Resolving zonepxy... wget https://raw.githubusercontent.com/udhos/jazigo/master/www/ok-small.png
10.22.32.13
Connecting to zonepxy
wget https://raw.githubusercontent.com/udhos/jazigo/master/www/GitHub-Mark-32px.pngProxy request sent, awaiting response... 200 OK
Length: 1112 (1.1K) [image/png]
Saving to: â€˜fail-small.png.1â€™

100%[===============================================================================================================================================================================================>] 1,112       --.-K/s   in 0s      

2023-08-03 08:28:11 (39.6 MB/s) - â€˜fail-small.png.1â€™ saved [1112/1112]

[root@malowntx-netengsrv02 www]# wget https://raw.githubusercontent.com/udhos/jazigo/master/www/ok-small.png
--2023-08-03 08:28:11--  https://raw.githubusercontent.com/udhos/jazigo/master/www/ok-small.png
Resolving zonepxy... connected.
Proxy request sent, awaiting response... 200 OK
Length: 1086 (1.1K) [image/png]
Saving to: â€˜ok-small.png.1â€™

100%[===============================================================================================================================================================================================>] 1,086       --.-K/s   in 0s      

2023-08-03 08:28:11 (50.3 MB/s) - â€˜ok-small.png.1â€™ saved [1086/1086]

[root@malowntx-netengsrv02 www]# wget https://raw.githubusercontent.com/udhos/jazigo/master/www/jazigo.css
--2023-08-03 08:28:11--  https://raw.githubusercontent.com/udhos/jazigo/master/www/jazigo.css
:8443... connected.
Proxy request sent, awaiting response... 200 OK
Length: 922 [text/plain]
Saving to: â€˜jazigo.css.1â€™

100%[===============================================================================================================================================================================================>] 922         --.-K/s   in 0s      

2023-08-03 08:28:11 (35.0 MB/s) - â€˜jazigo.css.1â€™ saved [922/922]

[root@malowntx-netengsrv02 www]# wget https://raw.githubusercontent.com/udhos/jazigo/master/www/GitHub-Mark-32px.png
--2023-08-03 08:28:13--  https://raw.githubusercontent.com/udhos/jazigo/master/www/GitHub-Mark-32px.png
Resolving zonepxy:8443... connected.
Proxy request sent, awaiting response... 200 OK
Length: 1714 (1.7K) [image/png]
Saving to: â€˜GitHub-Mark-32px.png.1â€™

100%[===============================================================================================================================================================================================>] 1,714       --.-K/s   in 0s      

2023-08-03 08:28:13 (10.1 MB/s) - â€˜GitHub-Mark-32px.png.1â€™ saved [1714/1714]

[root@malowntx-netengsrv02 www]# GOPATH/bin/jazigo -runOnce
-bash: GOPATH/bin/jazigo: No such file or directory
[root@malowntx-netengsrv02 www]#

**Comment by udhos** [comment]
Try:

~/bin/jazigo -runOnce

**Comment by tpolim008** [comment]
I tried both options as root and non root user to the sam issue.

***@***.*** ~]# cd $JAZIGO_HOME
***@***.*** ~]# ~/bin/jazigo -disableStdoutLog
-bash: /root/bin/jazigo: No such file or directory
***@***.*** ~]# cd
***@***.*** ~]# ~/bin/jazigo -disableStdoutLog
-bash: /root/bin/jazigo: No such file or directory
***@***.*** ~]# ~/bin/jazigo -runOnce
-bash: /root/bin/jazigo: No such file or directory
***@***.*** ~]# **$**GOPATH/bin/jazigo -runOnce
-bash: ***GOPATH/bin/jazigo: No such file or directory
***@***.*** ~]#

**Comment by udhos** [comment]
Sorry, I meant `~/go/bin/jazigo`.

The correct command to start jazigo depends on how you got the binary.

For instance, `~/go/bin/jazigo` works if you built the binary using directions below, producing the compiled binary at default location.

```bash
# quick start recipe
git clone https://github.com/udhos/jazigo ;# clone outside of GOPATH
cd jazigo
go install ./jazigo
mkdir etc repo log
JAZIGO_HOME=$PWD ~/go/bin/jazigo
```

If you downloaded the binary to another location, you ought either to invoke that full location or copy/move the binary to `~/go/bin` and then run `~/go/bin/jazigo`.
